name: pioneer
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  photo_view: ^0.14.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  assets:
    - assets/images/background_image.png
    - assets/images/app_icon.png
    - assets/images/background.png
    - assets/images/elitsa.jpg
    - assets/images/zhivko.jpg
    - assets/images/nikola.jpg
    - assets/images/alex.jpg
    - assets/images/photo1.jpg
    - assets/images/photo2.jpg
    - assets/images/photo3.jpg
    - assets/images/photo4.jpg
    - assets/images/photo5.jpg
    - assets/images/photo6.jpg
    - assets/images/photo7.jpg
    - assets/images/photo8.jpg
    - assets/images/photo9.jpg
    - assets/images/photo10.jpg
    - assets/images/photo11.jpg
    - assets/images/photo12.jpg
    - assets/images/photo13.jpg
    - assets/images/photo14.jpg
    - assets/images/photo15.jpg
    - assets/images/icon.png
    - assets/images/background_img1.png
    - assets/images/background_img2.png
  fonts:
    - family: Blanka
      fonts:
        - asset: fonts/Blanka-Regular.otf
 
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png" 
